### ISSUE TITLE
error while trying to update MTS

### ISSUE THREAD

**Issue by martenson** [galaxyproject/usegalaxy-playbook#27] opened 2017-05-01 03:37 UTC
```
TASK [galaxyprojectdotorg.galaxy_toolshed : Install additional Tool Shed config files (static)] ***
fatal: [radegast.galaxyproject.org]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'dest'\n\nThe error appears to have been in '/Users/marten/devel/git/usegalaxy-playbook/roles/galaxyprojectdotorg.galaxy_toolshed/tasks/static_setup.yml': line 7, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install additional Tool Shed config files (static)\n  ^ here\n"}
```

**Comment by chambm** [comment] 2017-06-26 15:13
Isn't this a dupe of your #23 ?

**Comment by natefoo** [comment] 2017-07-20 03:39
Indeed.

**Closed by natefoo** 2017-07-20 03:39 UTC

**Comment by martenson** [comment] 2017-07-31 17:40
@chambm lol, yes :D
