### ISSUE TITLE
Histogram of a numeric column

### ISSUE THREAD

**Issue by BJWiley233** [galaxyproject/usegalaxy-playbook#309] opened 2020-10-12 18:42 UTC
Hi,

I believe there may be a flaw in the "Histogram of a numeric column" tool.  This has to do with the "number of breaks".  I am pretty positive you are calling R `hist()` with breaks set to some calculation.  However I don't think the calculation is starting correctly.  For instance if I want to histogram on BED12 file where column 10 is the exon of the gene, i.e. a gene with 18 exons can have 1-18 listed in this column.  If I set the breaks to 18 in Galaxy it combines bin for exon 1-2 and there are only 17 bins.  This is because it is setting `breaks` to `c(1:18)` using maybe for instance the code below if my bed file is table in R called `ENm008`.

```
breaks=18
hist_breaks = seq(min(ENm008$V10), max(ENm008$V10), by=((max(ENm008$V10) - min(ENm008$V10))/(breaks - 1))) # giving c(1:18)
```
Instead it needs to do `min(column 10) - 1` in the `seq` function such as:

```
breaks=18
hist_breaks = seq(min(ENm008$V10) - 1, max(ENm008$V10), by=((max(ENm008$V10) - min(ENm008$V10))/(breaks - 1))) # giving c(0:18)
```
The this correctly gives 18 bins in my histogram for all 18 exons.  You can test this for any data set on transcript using exons file from UCSC in .bed format.

**Comment by jennaj** [comment] 2020-11-16 22:46
Hi @BJWiley233 I'm not able to reproduce but I also might not be understanding the issue correctly. This also isn't the best repository to report a tool bug.

Would you please report the problem to this tool's development repository? Providing a small example history will help, so we are all looking at the exact same test case (inputs, parameters, tool version): https://github.com/galaxyproject/tools-devteam/tree/master/tools/histogram

Place a link to this issue in the new issue, so we can keep the context. I'm going to close this out. If the tool is updated, it will get picked up and updated at the public Galaxy servers, including usegalaxy.org. 

Thanks!

**Closed by jennaj** 2020-11-16 22:46 UTC

**Comment by BJWiley233** [comment] 2020-11-17 01:37
Will do and provide a history. Thanks for the reply
